### ISSUE TITLE
Call to undefined method Neos\Flow\Mvc\ActionResponse::setHeader() in ThumbnailController.php

### ISSUE THREAD

**Issue by stepqom** [daniellienert/assetsource-nextcloud#5]
There seams to be a bug in ThumbnailController.php, maybe because of an api change (found setHeader only [here](https://github.com/neos/flow/commit/03b4fc73812a5817b6b6c11e3d1abda2fa86793e#diff-365369ea0a9cab20740d0ae6083b4dc7), was only included for a few hours ...) ?

Line 39 
        `$this->response->setHeader('Content-type', 'image/jpg');`
should be
        `$this->response->setContentType('image/jpg');`
So it works for me.

**Comment by daniellienert** [comment]
Hey @stepqom, thanks for reporting!
